(function(){var P=/\b[A-Z]\d{4}-\d{4}\b/i,last='',sent=0,noSince=0,noSent=false,sch=null;
function clean(v){return String(v||'').replace(/\u003c[^\u003e]*\u003e/g,' ').replace(/\s+/g,' ').trim()}
function tid(t){var m=clean(t).match(P);return m?m[0].toUpperCase():''}
function vis(e){if(!e)return false;var s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0}
function txt(e){return clean(e&&(e.innerText||e.textContent||e.getAttribute('title')||e.getAttribute('aria-label')))}
function q(a){var r=[];a.forEach(s=>{try{document.querySelectorAll(s).forEach(e=>r.push(e))}catch{}});return r}
function tablike(e){var c=String(e?.className||'').toLowerCase(),role=String(e?.getAttribute?.('role')||'').toLowerCase();return role==='tab'||c.includes('tab')||c.includes('active')||c.includes('selected')}
function clicked(start){var e=start,d=0;while(e&&d<8){var t=txt(e),id=tid(t);if(id&&tablike(e))return{ticketId:id,ticketTitle:t,source:'clicked-tab'};e=e.parentElement;d++}return null}
function closeClick(e){var c=e,d=0;while(c&&d<5){var all=(txt(c)+' '+clean(c.getAttribute&&c.getAttribute('title'))+' '+clean(c.getAttribute&&c.getAttribute('aria-label'))+' '+String(c.className||'')).toLowerCase();if(all==='x'||all==='×'||all.includes('close')||all.includes('sluit')||all.includes('x-tab-close'))return true;c=c.parentElement;d++}return false}
function active(){var scored=[];q(['[role="tab"][aria-selected="true"]','[aria-selected="true"]','[aria-current="page"]','.x-tab-active','.x-tab-selected','.tab.active','.tab.selected','[class*="tab"][class*="active"]','[class*="tab"][class*="selected"]']).forEach(e=>{if(!vis(e))return;var t=txt(e),id=tid(t);if(id)scored.push({ticketId:id,ticketTitle:t,score:100})});q(['h1','h2','[class*="title"]','[class*="header"]','[class*="caption"]']).forEach(e=>{if(!vis(e)||e.getBoundingClientRect().top>260)return;var t=txt(e),id=tid(t);if(id)scored.push({ticketId:id,ticketTitle:t,score:90})});var dt=tid(document.title);if(dt)scored.push({ticketId:dt,ticketTitle:clean(document.title),score:40});scored.sort((a,b)=>b.score-a.score);return scored[0]||null}
function sendT(t,force){if(!t)return;var n=Date.now();if(!force&&t.ticketId===last&&n-sent<2500)return;last=t.ticketId;sent=n;noSince=0;noSent=false;chrome.runtime.sendMessage({type:'TOPDESK_ACTIVE_TICKET_CHANGED',ticket:{ticketId:t.ticketId,ticketTitle:t.ticketTitle||t.ticketId,detectedUrl:location.href}}).catch(()=>{})}
function sendC(t){if(t)chrome.runtime.sendMessage({type:'TOPDESK_TICKET_CLOSED',ticket:{ticketId:t.ticketId,ticketTitle:t.ticketTitle||t.ticketId}}).catch(()=>{})}
function hasTab(){return q(['[role="tab"]','[class*="tab"]','.x-tab','.tab']).some(e=>vis(e)&&tid(txt(e)))}
function noTicketStable(){if(noSent)return;if(hasTab()){noSince=0;return}var text=clean(document.body?document.body.innerText:'');var list=text.includes('Openstaande')||text.includes('Selectie')||text.includes('Meldingen')||text.includes('Incidenten');if(!list){noSince=0;return}var n=Date.now();if(!noSince){noSince=n;return}if(n-noSince<2500)return;noSent=true;last='';chrome.runtime.sendMessage({type:'TOPDESK_NO_ACTIVE_TICKET'}).catch(()=>{})}
function check(force){var t=active();if(t){sendT(t,force);return}noTicketStable()}
function schedule(force,delay){clearTimeout(sch);sch=setTimeout(()=>check(!!force),delay||250)}
document.addEventListener('click',e=>{var t=clicked(e.target),c=closeClick(e.target);if(t&&c){sendC(t);noSince=0;noSent=false;schedule(true,900);setTimeout(()=>check(true),1600);return}if(t)sendT(t,true);schedule(true,450);setTimeout(()=>check(true),1000)},true);
new MutationObserver(()=>schedule(false,550)).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class','aria-selected','aria-current','title','style']});
chrome.runtime.onMessage.addListener(m=>{if(m&&m.type==='CHECK_TOPDESK_ACTIVE_TICKET')schedule(true,100)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(true,200)});window.addEventListener('focus',()=>schedule(true,200));schedule(true,300);setInterval(()=>schedule(false,450),2000);})();